workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          cd scannerV2/scannerV2
          flutter pub get

      - name: Build unsigned iOS archive
        script: |
          cd scannerV2/scannerV2
          flutter build ios --release --no-codesign

      - name: Copy archive to artifacts folder
        script: |
          mkdir -p artifacts
          cp -R scannerV2/scannerV2/build/ios/iphoneos/Runner.app artifacts/
          ls -la artifacts

    artifacts:
      - artifacts/Runner.app
