workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          cd scannerV2/scannerV2
          flutter pub get

      - name: Build IPA
        script: |
          cd scannerV2/scannerV2
          flutter build ipa --release --no-codesign

    artifacts:
      - scannerV2/scannerV2/build/ios/ipa/*.ipa
